apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-rest-api
    version: 0.0.1-SNAPSHOT
  name: hello-world-rest-api
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
        version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/hello-world-rest-api:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: hello-world-rest-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: hello-world-rest-api
  type: LoadBalancer

