# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: hello-world-rest-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 4,17 * * *'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-helm   # TODO: update to cluster name
  GKE_ZONE: us-central1-c       # TODO: update to cluster zone
  DEPLOYMENT_NAME: hello-world-rest-api  # TODO: update deployment name if changed in deployment.yaml
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 for hello-world-rest-api
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
#      - name: Build hello-world-rest-api with Maven
#        run: mvn -B clean install -P docker-build-push --file pom.xml
      - name: generate sonar report of the currency-service
        run: mvn sonar:sonar



